"""Make is_forum nullable

Revision ID: 53b415a896c2
Revises: 001
Create Date: 2025-08-25 19:04:19.787876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b415a896c2'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'is_forum',
                   existing_type=sa.BOOLEAN(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'is_forum',
                   existing_type=sa.BOOLEAN(),
                   nullable=False)
    # ### end Alembic commands ###
