"""Add reactions table

Revision ID: 6bcd19d12389
Revises: 53b415a896c2
Create Date: 2025-08-25 19:40:00.644930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcd19d12389'
down_revision = '53b415a896c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reaction_emoji', sa.String(length=100), nullable=False),
    sa.Column('is_big', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'msg_id', 'user_id', 'reaction_emoji')
    )
    op.create_index('ix_reactions_chat_date', 'reactions', ['chat_id', 'date'], unique=False)
    op.create_index('ix_reactions_emoji', 'reactions', ['reaction_emoji'], unique=False)
    op.create_index('ix_reactions_msg', 'reactions', ['chat_id', 'msg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reactions_msg', table_name='reactions')
    op.drop_index('ix_reactions_emoji', table_name='reactions')
    op.drop_index('ix_reactions_chat_date', table_name='reactions')
    op.drop_table('reactions')
    # ### end Alembic commands ###
