"""Add composite foreign key constraint to reactions

Revision ID: a874548e50e2
Revises: 6bcd19d12389
Create Date: 2025-08-25 19:49:38.166096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a874548e50e2'
down_revision = '6bcd19d12389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip the user_id nullable change since it's part of the primary key
    # op.alter_column('reactions', 'user_id',
    #            existing_type=sa.BIGINT(),
    #            nullable=True)
    op.create_foreign_key('fk_reactions_message', 'reactions', 'messages', ['chat_id', 'msg_id'], ['chat_id', 'msg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_reactions_message', 'reactions', type_='foreignkey')
    # Skip the user_id nullable change since it was skipped in upgrade
    # op.alter_column('reactions', 'user_id',
    #            existing_type=sa.BIGINT(),
    #            nullable=False)
    # ### end Alembic commands ###
