"""Recreate reactions table with proper structure

Revision ID: d25c72be7a85
Revises: a874548e50e2
Create Date: 2025-08-25 19:50:34.190022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd25c72be7a85'
down_revision = 'a874548e50e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing reactions table first
    op.drop_index('ix_reactions_msg', table_name='reactions')
    op.drop_index('ix_reactions_emoji', table_name='reactions')
    op.drop_index('ix_reactions_chat_date', table_name='reactions')
    op.drop_table('reactions')
    
    # Recreate with proper structure
    op.create_table('reactions',
    sa.Column('reaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('reaction_emoji', sa.String(length=100), nullable=False),
    sa.Column('is_big', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id', 'msg_id'], ['messages.chat_id', 'messages.msg_id'], name='fk_reactions_message'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reaction_id')
    )
    op.create_index('ix_reactions_chat_date', 'reactions', ['chat_id', 'date'], unique=False)
    op.create_index('ix_reactions_emoji', 'reactions', ['reaction_emoji'], unique=False)
    op.create_index('ix_reactions_msg', 'reactions', ['chat_id', 'msg_id'], unique=False)
    op.create_index('ix_reactions_user_msg_emoji', 'reactions', ['user_id', 'chat_id', 'msg_id', 'reaction_emoji'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reactions_user_msg_emoji', table_name='reactions')
    op.drop_index('ix_reactions_msg', table_name='reactions')
    op.drop_index('ix_reactions_emoji', table_name='reactions')
    op.drop_index('ix_reactions_chat_date', table_name='reactions')
    op.drop_table('reactions')
    # ### end Alembic commands ###
